version: "1.0"
services:
 frontend_app:
  container_name: frontend
  image: frontend:react 
  build: ./frontend
  ports:
   - "5173:5173"

 backend_api:
  container_name: backend
  image: backend:django
  build: ./backend
  ports:
   - "8000:8000"